# GET http://localhost:3000/songs/

# GET http://localhost:3000/songs/1

# PUT http://localhost:3000/songs/1

POST http://localhost:3000/songs/
Content-Type: application/json

{
    "title": "Husn",
    "artists": ["Anuv Jain"],
    "releasedDate": "2024-12-10",
    "duration": "03:40"
}